version: "3"
services:
  interview-ready-backend:
    image: jayabrata180/interview-ready-backend:latest
    container_name: "interview-ready-backend"
    environment:
      - DATABASE_URL=postgresql://postgres:~}8{[#_nKqg?<KU2@34.93.180.39:5432/postgres
      - JWT_SECRET_KEY=asdfgh
    depends_on:
      - db
  interview-ready-frontend:
    image: jayabrata180/interview-ready-frontend:latest
    container_name: "interview-ready-frontend"
    depends_on:
      - interview-ready-backend
  proxy:
    image: jayabrata180/interview-ready-nginx:latest
    container_name: "interview-ready-nginx"
    restart: always
    ports:
      - "80:80"
  db:
    image: postgres:latest
    container_name: "postgres_db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "5433:5432"  
volumes:
  postgres_data: