version: "3"
services:
  interview-ready-backend:
    image: jayabrata180/interview-ready-backend:latest
    container_name: "interview-ready-backend"

  interview-ready-frontend:
    image: jayabrata180/interview-ready-frontend:latest
    container_name: "interview-ready-frontend"
    depends_on:
      - interview-ready-backend
  proxy:
    image: jayabrata180/interview-ready-proxy:latest
    container_name: "interview-ready-proxy"
    restart: always
    ports:
      - "80:80"
